In [ ]:
#Experiment 9:
#Unit 2:Tools For EDA
#Aim: Study Of Numpy Library
#Shravya Srivastava
#PRN: 25070123106

In [ ]:
#numpy, create arrays, and perform numerical operations
#We use Numpy because its faster than lists,and used for numerical compulation


In [2]:
#declaring Numpy
#we can print matrices, find its type and dimensions using numpy library
import numpy as np

a=np.array([1,10,20,30,40,50,500])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

#finding dimension of array

print(a.ndim)
print(b.ndim)

#shape gives no of rows and columns

print(a.shape)
print(b.shape)

#finding datatypes of each matrix
#if we change int number in matrix into decimal, then it will give its datatype as float

print(a.dtype)
print(b.dtype)

#using inbuilt functions using Numpy

print(np.zeros((2,3))) #makes 0 matrix

print(np.ones((3,3)))# makes 1 matrix

print(np.eye((3))) #eye- identity matrix

print(np.arange(1,10,2)) # arrage format = (starting range,stops at n-1, gap)

print(np.linspace(0,1,4)) #step size = 1-0/4-1 = 1/3 giving answer,it creates equally spaced matrix of 4 elements from 0 to 1

print(b*2) #multipilies each element by2

print(a+5) #adds 5 to every element

print(np.median(a)) #calculation of median

print(np.std(a)) #calculating standerd deviation

print(np.mean(a)) # mean calc of matrix

print(np.max(a))# maximum of matrix

print(np.sum(a))# sum

print(np.min(a))# min



[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64
int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[0.         0.33333333 0.66666667 1.        ]
[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]
30.0
166.88661677061722
93.0
500
651
1
